[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
;monitor_speed = 74880 
lib_deps = knolleary/PubSubClient@^2.8

; === THÊM 2 DÒNG NÀY VÀO ===
monitor_echo = yes               ; Cho phép hiển thị các ký tự em đang gõ lên màn hình
monitor_filters = send_on_enter  ; Đóng gói cả cụm chữ và tự động thêm '\n' khi nhấn Enter